### ISSUE TITLE
Issues with Bower install

### ISSUE THREAD

**Issue by randywinch** [mikepugh/AngularGeoFire#8]
I am getting an error when trying to install this module through Bower. Here is the error:

bower angularGeoFire#\*          cached git://github.com/mikepugh/AngularGeoFire.git#3.0.0
bower angularGeoFire#\*        validate 3.0.0 against git://github.com/mikepugh/AngularGeoFire.git#*
bower geofire#~3.x          not-cached git://github.com/firebase/geofire.git#~3.x
bower geofire#~3.x             resolve git://github.com/firebase/geofire.git#~3.x
bower angular#~1.2.5            cached git://github.com/angular/bower-angular.git#1.2.23
bower angular#~1.2.5          validate 1.2.23 against git://github.com/angular/bower-angular.git#~1.2.5
bower geofire#~3.x        ENORESTARGET No tag found that was able to satisfy ~3.x

I checked the geofire repo and it looks like js code is now in geofire-js.

**Comment by mikepugh** [comment]
This should be fixed now! The GeoFire team got their bower package pointing to the correct repo now. Thanks!
